
var CabLabels = {};

CabLabels.en = {

	"common.cancel":"Cancel",
	"common.reload":"Reload",
	"common.edit":"Edit",
	"common.update":"Update",
	"common.delete":"Delete",
	"common.add":"Add",
	"common.hide":"Hide",
	"common.noReq": "No requests",
	"common.confirmReq": "Confirm request",
	"common.delReq": "Delete request",
	"common.inReq":"Wait...",
	"common.send":"Send",
	"common.client":"Client",
	"common.op":"Operator",
	
	"common.msg.dataUpdated":"Data was updated",
	
	"col.accountId": "account id",
	"col.created": "created",
	"col.actions": "actions",
	"col.login":"login",
	"col.chatName":"chat name",
	"col.privileges":"privileges",
	"col.type":"type",
	"col.description":"description",
	"col.status":"status",
	"col.date":"date",
	"col.amount":"amount",

	"tariffName.1": "SYSTEM",
	"tariffDesc.1": "",
	"tariffName.2": "BASIC",
	"tariffDesc.2": "Basic tariff. $5 per month, max 2 operators for account",
	"tariffName.4": "EXTRA",
	"tariffDesc.4": "Extra tariff. $15 per month, max 10 operators for account",
	"tariffName.5": "EXTRA",
	"tariffDesc.5": "Extra tariff. $20 per month, max 10 operators for account",
	
	"tariffChange.already":"You already have current tariff for the account",
	"tariffChange.msg.updated":"Tariff Updated!",
	"tariffChange.msg.updatedDescBegin":"The cost of using the old tariff in this month was",
	"tariffChange.msg.updatedDescEnd":"For more information see",
	"tariffChange.msg.billingLink":"Billing Tab",
	"tariffChange.msg.paused":"Account is frozen!",
	"tariffChange.msg.unpaused":"Account is active!",
	
	"status.cantChange":"Can't change online status for",
	
	"users.deleteTitle":"User will be deleted from account users",
	
	"chat.from":"From: ",
	"chat.noNickname":"No chat name",
	
	"feeds.empty":"Empty",
	
	"billing.emptyList":"No payments",
	"billing.inputPay":"INPUT",
	"billing.outputPay":"OUTPUT",
	"billing.payName.bonus":"START BONUS",
	"billing.payName.userPay":"USER PAYMENT",
	"billing.payName.invoice":"INVOICE",
	"billing.msg.payConfirmed":"Payment confirmed",
	"billing.msg.accUnblocked":"Your accounts was unblocked. Reload page to see all changes.",
	"billing.msg.payCanceled":"Payment request was canceled",
	"billing.msg.redirectToPaypal":"Redirecting to Paypal Login Page...",
	"billing.msg.redirectTo2Checkout":"Redirecting to 2Checkout...",
	
	"accInfo.msg.notifyUpdated":"Notifications updated",
	
	"access.msg.reload":"Reload current page to see all access changes",
	
	"chats.newMessagesTitle":"New messages:",

	"notify.msgPermitted": "Notifications enabled!",
	"notify.newMessage":"You have new messages!",

	
	"":""
};

CabLabels.ru = {

	"common.cancel":"Отмена",
	"common.reload":"Обновить",
	"common.edit":"Редактировать",
	"common.update":"Обновить",
	"common.delete":"Удалить",
	"common.add":"Добавить",
	"common.hide":"Скрыть",
	"common.noReq": "Нет запросов",
	"common.confirmReq": "Подтвердить запрос",
	"common.delReq": "Удалить запрос",
	"common.inReq":"Обработка...",
	"common.send":"Отправить",
	"common.client":"Клиент",
	"common.op":"Оператор",
	
	"common.msg.dataUpdated":"Данные обновлены",
	
	"col.accountId": "идентиф. аккаунта",
	"col.created": "создано",
	"col.actions": "действия",
	"col.login":"логин",
	"col.chatName":"псевдоним",
	"col.privileges":"привилегии",
	"col.type":"тип",
	"col.description":"описание",
	"col.status":"статус",
	"col.date":"дата",
	"col.amount":"сумма",

	"welcome.title":"Добро пожаловать в Live Chats!",
	"welcome.info":"<b>Создайте себе аккаунт</b> или <b>подайте заявку в операторы</b>.",
	
	"newAcc.title":"Название аккаунта (пример: my-site.com)",
	"newAcc.name.placeholder":"Введите название",
	"newAcc.name.title":"Название аккаунта",
	"newAcc.checkbox":"Сделать меня оператором",
	"newAcc.create":"Создать",
	
	"addOp.title":"Отправить запрос владельцу аккаунта",
	"addOp.accId":"Введите идентификатор аккаунта",
	"addOp.btn":"Отправить",
	"addOp.sended.title":"Отправленные запросы",
	"addOp.update":"Обновить",
	"addOp.deleteReq":"Удалить запрос",
	
	"user.newEmail":"Новый email",
	"user.newLogin":"Новый логин",
	"user.newPsw":"Новый пароль",
	"user.confirmChangesPsw":"Текущий пароль для подтверждения изменений",
	"user.curPsw":"Введите текущий пароль",
	"user.update":"Обновить данные",
	"user.reset":"Вернуть текущие значения",
	
	"selectTariff.label":"Тариф",
	"tariffName.1": "SYSTEM",
	"tariffDesc.1": "",
	"tariffName.2": "Базовый",
	"tariffDesc.2": "Базовый тариф. $5 в месяц, 2 оператора максимум",
	"tariffName.4": "Экстра",
	"tariffDesc.4": "Экстра тариф. $15 в месяц, 10 операторов максимум",
	"tariffName.5": "Экстра",
	"tariffDesc.5": "Экстра тариф. $20 в месяц, 10 операторов максимум",
	
	"chats.conToChats":"Соединение с сервером...",
	"chats.cantConToChats":"Не удалось соединиться с сервером.",
	"chats.retryCon":"Попробовать снова",
	"chats.blocked.title":"Внимание!",
	"chats.blocked.desc":"Аккаунт блокирован. Возможно его владелец имеет отрицательный баланс.",
	"chats.paused":"Аккаунт заморожен. Операции с ним ограничены.",
	"chats.unpaused.btn":"Разморозить аккаунт",
	"chats.unpaused.btnDesc":"для работы с ним.",
	"chats.acc.load":"Получение данных по аккаунту...",
	"chats.acc.loadError":"Не удалось получить данные по аккаунту.",
	"chats.acc.retryCon":"Попробовать снова",
	"chats.conProblems":"Проблемы соединения с сервером. Требуется переподключение.",
	"chats.reconnect":"Переподключиться",
	
	"chats.tab.active":"Активные чаты",
	"chats.tab.hist":"История",
	"chats.tab.feedback":"Отзывы",
	"chats.tab.accInfo":"Настройки",
	"chats.tab.users":"Пользователи",
	
	"accInfo.base":"Базовые",
	"accInfo.id":"Идентификатор аккаунта",
	"accInfo.created":"Создан",
	"accInfo.name":"Название",
	"accInfo.nameEnter":"Введите название",
	"accInfo.update":"Обновить",
	
	"accInfo.tariff":"Тариф",
	"accInfo.tariff.name":"Название тарифа",
	"accInfo.tariff.monthPrice":"Месячная стоимость",
	"accInfo.tariff.desc":"Для подробной информации см. раздел ",
	"accInfo.tariff.billing":"Баланс",
	"accInfo.tariff.maxOps":"Макс. операторов",
	"accInfo.tariff.change":"Изменить тариф или заморозить аккаунт",
	"accInfo.tariff.unpaused":"Разморозить аккаунт",
	
	"tariffChange.warning":"Внимание!",
	"tariffChange.payInfo":"При смене тарифа будет произведен расчет за использование старого тарифа в текущем месяце.",
	"tariffChange.dayLimitStart":"Вы можете менять тариф только",
	"tariffChange.dayLimitEnd":"раза в день",
	"tariffChange.already":"У вас уже выбран данный тариф",
	"tariffChange.update":"Сменить тариф",
	"tariffChange.pause":"Заморозить аккаунт",
	"tariffChange.unpause":"Разморозить аккаунт",
	"tariffChange.msg.updated":"Тариф обновлен!",
	"tariffChange.msg.updatedDescBegin":"Стоимость использования старого тарифа составила",
	"tariffChange.msg.updatedDescEnd":"Для подробной информации см. раздел",
	"tariffChange.msg.billingLink":"Баланс",
	"tariffChange.msg.paused":"Аккаунт заморожен!",
	"tariffChange.msg.unpaused":"Аккаунт активен!",
	
	"accInfo.emailNotify":"Оповещение по email",
	"accInfo.emailFeedForOps":"Новые отзывы для операторов",
	"accInfo.msg.notifyUpdated":"Оповещения обновлены",
	
	"accInfo.clientCode":"Клиентский код",
	"accInfo.clientCodeDesc":"Для добавления чата на ваш сайт используйте этот javascript-блок. \n\
		Он начинает с &lt;script> и заканчивается &lt;/script>. \n\
		<p>Не редактируйте этот блок, просто скопируйте его на те страницы, где вы хотите видеть чат. \n\
		<br>Добавьте его сразу перед закрывающимся тегом &lt;/head>.",
	
	"accInfo.clientCodeCheck":"Перезагрузите вашу страницу в браузере. Если появился блок \"Задайте вопрос!\", значит чат добавлен успешно!",
	"accInfo.seeDocs":"Для большей информации см. раздел ",
	"accInfo.docsLink":"Документация",
	
	"users.add":"Добавить пользователя",
	"users.reqs":"Запросы на добавление",
	"users.enterNickname":"Введите псевдоним",
	"users.priv.owner":"Владелец",
	"users.priv.moder":"Модератор",
	"users.priv.op":"Оператор",
	"users.deleteTitle":"Пользователь будет удален из данного аккаунта",
	"users.enterLoginOrEmail":"Введите логин или email",
	"users.loginOrEmail":"Логин или email",
	
	"status.wait":"Обработка...",
	"status.youOnline":"Вы ОНЛАЙН",
	"status.youOffline":"Вы ОФФЛАЙН",
	"status.online":"ОНЛАЙН",
	"status.offline":"ОФФЛАЙН",
	"status.change":"Изменить на",
	"status.global":"Глобальный статус",
	"status.changeGlobal":"Глобально",
	"status.cantChange":"Не удалось изменить статус для",
	"onlineOps":"Операторов онлайн:",
	
	"chat.mustTake":"Вы должны взять чат перед отправкой сообщения.",
	"chat.alreadyHasOp":"Чат уже взят другим оператором. Для отправки сообщения вы тоже должны взять этот чат.",
	"chat.take":"Взять",
	"chat.closedInfo":"Чат завершен. Вы не можете добавлять новые сообщения.",
	"chat.from":"Источник: ",
	"chat.sendInfo": "Введите сообщение и нажмите Отправить или <Ctrl> + <Enter>",
	"chat.noNickname":"Нет псевдонима",
	"chat.closed":"ЗАВЕРШЕН",
	
	"hist.showLogs":"Показать логи",
	"feed.from":"Источник",
	"feed.name":"Имя",
	"feed.email":"Email",
	"feed.created":"Создано",
	"feed.info":"Информация",
	"feed.msg":"Сообщение",
	"feed.show":"Показать отзывы",
	"feeds.empty":"Пусто",
	
	"billing.curBal":"Текущий баланс:",
	"billing.confirmPay":"Подтвердить платеж",
	"billing.newPay":"Новый платеж",
	"billing.payments":"Платежи",
	"billing.payment":"Платеж",
	"billing.payByPaypal":"Оплата",
	"billing.youSelected":"Вы выбрали:",
	"billing.pay":"Оплатить",
	"billing.emptyList":"Нет платежей",
	"billing.inputPay":"Входящий",
	"billing.outputPay":"Исходящий",
	"billing.payName.bonus":"Стартовый бонус",
	"billing.payName.userPay":"Пополнение",
	"billing.payName.invoice":"Счет",
	"billing.status.CREATED":"Создан",
	"billing.status.WAIT":"В обработке",
	"billing.status.COMPLETED":"Завершен",
	"billing.status.ERROR":"Ошибка",
	"billing.status.RETURNED":"Возвращен",
	"billing.msg.payConfirmed":"Платеж подтвержден",
	"billing.msg.accUnblocked":"Ваш аккаунт разблокирован. Обновите страницу для просмотра всех изменений.",
	"billing.msg.payCanceled":"Платеж отменен",
	"billing.msg.redirectToPaypal":"Переход на Paypal для оплаты...",
	"billing.msg.redirectTo2Checkout":"Переход на 2Checkout для оплаты...",
	
	"access.msg.reload":"Обновите страницу для просмотра всех изменений",
	
	"chats.newMessages":"Новые сообщения!",
	"chats.newMessagesTitle":"Новые сообщения:",

	"notify.msgPermitted": "Уведомления включены!",
	"notify.newMessage":"У вас есть новые сообщения!",


	"":""
};